// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookContainer': string;
  'books': string;
  'imgContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
